[3630102/90002]_<SaskovLev>_<A25>
motorny/alg-ds pull request #10
Opened 2020-10-03 16:54 UTC by levs2001

1я лабораторная работа.

2020-10-03 20:24 UTC, motorny requested changes
Добрый день,
Исправьте, пожалуйста, комментарии

2020-10-03 20:24 UTC, motorny commented on lab-1/Lab1_3sem/listInit.c
> +		for (pointer = 0; pointer < isize && pointer < strlen(word2compare) && pointer < strlen(word); pointer++) {
`strlen` будет вызываться 2 раза на каждой итерации цикла - это крайне неэффективно.
Почему не подошел обычный `strcmp`?

2020-10-03 20:24 UTC, motorny commented on lab-1/Lab1_3sem/Source.c
> +  file = fopen("D:\\Programms\\ForLab1_3sem\\List.txt", "r");
Используйте, пожалуйста, относительный путь, а еще лучше - путь из аргументов командной строки.

2020-10-03 20:24 UTC, motorny commented on lab-1/Readme
> +Запрос «И» «И» «» выдает первую фамилию в списке
К сожалению, не смог найти, где выполнен последний пункт задания с поиском по списку на основе первых букв.

2020-10-04 16:48 UTC, motorny commented
Ок, зачтено!

2020-11-03 19:02 UTC, closed without merging

2020-11-03 19:02 UTC, levs2001 commented
1я лабораторная закончена, для 2й создам новый pull request