[3630102/90001]_KozhevnikovaDG_A19
motorny/alg-ds pull request #8
Opened 2020-10-02 19:09 UTC by diakozhh

First pull request

2020-10-03 20:03 UTC, motorny requested changes
Добрый день!

Опишите, пожалуйста, почему вы выбрали именно этот алгоритм, какая его временная сложность в лучшем/худшем случаях, а также назовите альтернативные алгоритмы, которые тоже было бы рационально использовать для этой задачи

2020-10-03 20:03 UTC, motorny commented on lab-1/test.cpp
> +  tmp = popFront(l);
Тест непоказательный - неизвестно, какая из функций ошибется.

Функцию изъятия необходимо проверять список вручную
Удобно написать вспомогательную функцию, которая создает список.

Такое же замечание еще к нескольким тестам ниже

2020-10-03 20:03 UTC, motorny commented on lab-1/test.cpp
> +  insertBeforeElement(l, elem, "Element");
Аналогичный комментарий относится к этому тесту и еще нескольким тестам ниже.
Исправьте, пожалуйста

2020-10-04 16:51 UTC, diakozhh commented on lab-1/test.cpp
> +  tmp = popFront(l);
Если я правильно понимаю, то проблема в том, что что я использую createList и pushBack? т.е. нужно вручную написать createList в тестовом файле и вручную записать эти элементы в список, не используя проверяемые функции, и это относится к другим тестам?

2020-10-04 16:52 UTC, diakozhh commented on lab-1/test.cpp
> +  tmp = popFront(l);
> Тест непоказательный - неизвестно, какая из функций ошибется.
> 
> Функцию изъятия необходимо проверять список вручную
> Удобно написать вспомогательную функцию, которая создает список.
> 
> Такое же замечание еще к нескольким тестам ниже

Если я правильно понимаю, то проблема в том, что что я использую createList и pushBack? т.е. нужно вручную написать createList в тестовом файле и вручную записать эти элементы в список, не используя проверяемые функции, и это относится к другим тестам?

2020-10-05 10:12 UTC, diakozhh commented
> Добрый день!
> 
> Опишите, пожалуйста, почему вы выбрали именно этот алгоритм, какая его временная сложность в лучшем/худшем случаях, а также назовите альтернативные алгоритмы, которые тоже было бы рационально использовать для этой задачи

Потому что структура данных "двусвязный список" оптимальна для добавления в любое место. Временная сложность сортировки вставками благодаря этому в худшем случае O(N^2) а в лучшем O(N) . Возможно стоило бы использовать MergeSort.

2020-10-05 18:58 UTC, diakozhh commented on lab-1/DLL.c
> +  ins = (node_t*)malloc(sizeof(node_t));
> Отсутсвтует проверка на отказ в выделении памяти.

Это и замечания ниже исправлены

2020-10-08 17:01 UTC, motorny commented on lab-1/test.cpp
> +  tmp = popFront(l);
Добрый день,
Следует вручную записать элементы в список, манипулируя указателями, создав список на 2-3 элемента. Сделать из этого вспомогательную функцию и использовать далее в тестах.

2020-10-08 17:02 UTC, motorny reviewed
Ок, зачтено!

2020-11-10 17:34 UTC, closed without merging